config/routes.rb
Rails.application.routes.draw do

  resources :users
  match '/signup', to: 'users#new', via: :get

  match '/contact', to: 'pages#contact',via: :get
  match '/about',   to:'pages#about',via: :get
  match '/help',    to: 'pages#help',via: :get
  root to: 'pages#home',via: :get

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  nom        :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base

  email_regex = /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/
  attr_accessor :password


  validates :nom, :presence => true,
                  :length => { :maximum => 25 }
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }

  before_save :encrypt_password

  def has_password?(password_soumis)
    encrypted_password == encrypt(password_soumis)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  private

  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password)
  end

  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @titre = "Acceuil"
  end

  def contact
    @titre = "Contact"
  end

  def about
    @titre ="A Propos"
  end

  def help
    @titre = "Aide"

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @titre = @user.nom
  end

  def new
    @user = User.new
    @titre = "Inscription"
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Bienvenue dans l'Application Exemple!"
      redirect_to @user
    else
      @titre = "Inscription"
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:nom, :email, :password, :salt, :encrypted_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def titre
    base_titre = 'Simple App du Tutoriel Ruby on Rails'
    if @titre.nil?
      base_titre
    else
      "#{base_titre} | #{@titre}"
    end
  end

  def logo
    logo = image_tag("logo.png", :alt => 'Application exemple', :class => "round")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.nom,
                       :class => 'gravatar',
                       :gravatar => options)
  end



end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "À Propos", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Tutoriel Rails</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
<nav class="round">
  <ul>
    <li><%= link_to "Accueil", root_path %></li>
    <li><%= link_to "Aide", help_path %></li>
    <li><%= link_to "Inscription", '#' %></li>
    <li><%= link_to "À Propos", about_path %></li>
  </ul>
</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= titre %></title>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets' %>

</head>
<body>
<div class="container">
    <%= render 'layouts/header' %>
  <section class="round">
    <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </section>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>À Propos de nous</h1>
<p>
  <a href="http://railstutorial.org/">Le Tutoriel Ruby on Rails</a>
  est un projet de livre et de screencasts pour apprendre le développement web
  avec <a href="http://rubyonrails.org/">Ruby on Rails</a>. Ceci
  est l'Application Exemple du tutoriel.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial à propos de l'Application Exemple à
  <a href="http://railstutorial.org/feedback">feedback page</a>.
</p>

app/views/pages/help.html.erb
<h1> Page d'aide</h1>
<p>
  Voici une page d'aide que je viens de créer suite à la demande de plusieurs utilisateurs
  voici des lien qui pour vous rediriger :
  <br>
</p>

app/views/pages/home.html.erb
<h1>Simple App</h1>
<p>
  Ceci est la page <%= @titre %>  de l'Application Exemple du
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>.
</p>

<%= link_to "Sign up now !", signup_path, :class => "signup_button round" %>

app/views/shared/_error_messages.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "erreur") %>
        ont empêché d'enregistrer votre inscription</h2>
      <p>Merci de corriger ces champs :</p>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/new.html.erb
<h1>Inscription</h1>

<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    <div class="field">
      <%= f.label :nom %><br />
      <%= f.text_field :nom %>
    </div>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation, "Confirmation" %><br />
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= f.submit "Inscription" %>
    </div>
<% end %>

app/views/users/show.erb
<table class="profile" summary="Information profil">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.nom %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Nom</strong> <%= @user.nom %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>